site_name: My Life Notes
theme:
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
  name: material
  palette:
    - scheme: slate
      primary: white
      accent: light grey

nav:
  - Home: index.md
  - Games: 
    - Journal: gaming/df.md


